[package]
name = "skiplist"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.4.1"
bitintr = "0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false